/**
 * Generate every derived artifact from the canonical catalog (src/authz/catalog.ts):
 *
 *   docs/authorization/catalog.json      machine-readable catalog (served by GET /authz/catalog too)
 *   docs/authorization/catalog.md        human-readable catalog
 *   docs/authorization/matrix.json       system roles + templates × permission × scope
 *   docs/authorization/matrix.md         the same as tables (security specification)
 *   ../sanctum-frontend/lib/authz/catalog.generated.ts
 *   ../sanctum-flutter/lib/authz/catalog.g.dart
 *
 * Run: pnpm authz:generate   (CI: pnpm authz:generate --check fails on drift)
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  CATEGORIES,
  PERMISSIONS,
  ROLE_TEMPLATES,
  SCOPES,
  SCOPE_LABELS,
  SYSTEM_ROLES,
  publicCatalog,
  type Grant,
} from '../src/authz/catalog.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const check = process.argv.includes('--check');
let drift = false;

function emit(file: string, content: string): void {
  const abs = path.resolve(root, file);
  if (check) {
    const current = existsSync(abs) ? readFileSync(abs, 'utf8') : '';
    if (current.replace(/\r\n/g, '\n') !== content) {
      console.error(`drift: ${file}`);
      drift = true;
    }
    return;
  }
  if (!existsSync(path.dirname(abs))) {
    console.warn(`skip (missing dir): ${file}`);
    return;
  }
  writeFileSync(abs, content);
  console.log(`wrote ${file}`);
}

if (!check) {
  for (const dir of ['../sanctum-frontend/lib/authz', '../sanctum-flutter/lib/authz']) {
    if (existsSync(path.resolve(root, path.dirname(dir)))) mkdirSync(path.resolve(root, dir), { recursive: true });
  }
}

const catalog = publicCatalog();
const HEADER = 'GENERATED by sanctum-backend/scripts/authz-generate.ts from src/authz/catalog.ts — do not edit.';

// ---------------------------------------------------------------- catalog.json / .md
emit('docs/authorization/catalog.json', JSON.stringify(catalog, null, 2) + '\n');

{
  const lines: string[] = [
    '# Permission catalog',
    '',
    `> ${HEADER}`,
    `> Catalog version \`${catalog.version}\` · ${PERMISSIONS.length} permissions.`,
    '',
    '| Scope | Meaning |',
    '|---|---|',
    ...catalog.scopes.map((s) => `| \`${s.key}\` | ${s.description} |`),
    '',
  ];
  for (const c of CATEGORIES) {
    const ps = PERMISSIONS.filter((p) => p.category === c.key);
    if (!ps.length) continue;
    lines.push(`## ${c.label}`, '', '| Permission | Description | Scopes | Actors | Sensitive | Requires |', '|---|---|---|---|---|---|');
    for (const p of ps) {
      lines.push(
        `| \`${p.key}\` | ${p.description} | ${p.scopes.join(', ')} | ${p.actors.join(', ')} | ${p.sensitive ? '⚠' : ''} | ${p.requires.map((r) => `\`${r}\``).join(', ')} |`,
      );
    }
    lines.push('');
  }
  emit('docs/authorization/catalog.md', lines.join('\n'));
}

// ---------------------------------------------------------------- matrix
type MatrixRole = { key: string; name: string; kind: 'system' | 'template'; actorType: string; grants: Grant[] };
const matrixRoles: MatrixRole[] = [
  ...SYSTEM_ROLES.map((r) => ({ key: r.key, name: r.name, kind: 'system' as const, actorType: r.actorType, grants: r.grants() })),
  ...ROLE_TEMPLATES.map((t) => ({ key: t.key, name: t.name, kind: 'template' as const, actorType: t.actorType, grants: t.grants })),
];
const matrix = {
  version: catalog.version,
  note: 'Default grants for new agencies (system roles) and role templates. Existing agencies may have edited roles.',
  roles: matrixRoles.map((r) => ({
    key: r.key,
    name: r.name,
    kind: r.kind,
    actorType: r.actorType,
    grants: Object.fromEntries(
      PERMISSIONS.map((p) => [p.key, r.grants.filter((g) => g.permission === p.key).map((g) => g.scope)]).filter(
        ([, s]) => (s as string[]).length,
      ),
    ),
  })),
};
emit('docs/authorization/matrix.json', JSON.stringify(matrix, null, 2) + '\n');

{
  const staff = matrixRoles.filter((r) => r.actorType === 'staff');
  const client = matrixRoles.filter((r) => r.actorType === 'client');
  const abbr: Record<string, string> = { own: 'own', assigned: 'asg', project: 'prj', client: 'cli', organization: 'org' };
  const cell = (r: MatrixRole, key: string) =>
    r.grants.filter((g) => g.permission === key).map((g) => abbr[g.scope]).sort().join('+') || '—';
  const table = (rs: MatrixRole[], actor: 'staff' | 'client') => {
    const out = [`| Permission | ${rs.map((r) => `${r.name}${r.kind === 'template' ? ' *(t)*' : ''}`).join(' | ')} |`, `|---|${rs.map(() => '---').join('|')}|`];
    for (const c of CATEGORIES) {
      const ps = PERMISSIONS.filter((p) => p.category === c.key && p.actors.includes(actor));
      if (!ps.length) continue;
      out.push(`| **${c.label}** |${rs.map(() => ' ').join('|')}|`);
      for (const p of ps) out.push(`| \`${p.key}\` | ${rs.map((r) => cell(r, p.key)).join(' | ')} |`);
    }
    return out;
  };
  const lines = [
    '# Authorization matrix',
    '',
    `> ${HEADER}`,
    '',
    'Default grants per system role and template (*(t)* = template, not a stored role).',
    `Scopes: ${SCOPES.map((s) => `\`${abbr[s]}\` = ${SCOPE_LABELS[s]}`).join(', ')}; — = not granted.`,
    'Object-level policies (docs/authorization/README.md §G) apply on top: e.g. no self-approval, state machines, tenant binding.',
    '',
    '## Staff roles',
    '',
    ...table(staff, 'staff'),
    '',
    '## Client roles',
    '',
    ...table(client, 'client'),
    '',
  ];
  emit('docs/authorization/matrix.md', lines.join('\n'));
}

// ---------------------------------------------------------------- web client
{
  const ts = [
    `// ${HEADER}`,
    '/* eslint-disable */',
    '',
    `export const CATALOG_VERSION = ${JSON.stringify(catalog.version)};`,
    '',
    `export const SCOPES = ${JSON.stringify(SCOPES)} as const;`,
    'export type Scope = (typeof SCOPES)[number];',
    '',
    'export const PERMISSION_KEYS = [',
    ...PERMISSIONS.map((p) => `  ${JSON.stringify(p.key)},`),
    '] as const;',
    'export type Permission = (typeof PERMISSION_KEYS)[number];',
    '',
    'export interface PermissionMeta {',
    '  key: Permission;',
    '  resource: string;',
    '  action: string;',
    '  category: string;',
    '  label: string;',
    '  description: string;',
    '  scopes: Scope[];',
    "  actors: Array<'staff' | 'client'>;",
    '  sensitive: boolean;',
    '  requires: Permission[];',
    '}',
    '',
    `export const PERMISSIONS: PermissionMeta[] = ${JSON.stringify(catalog.permissions, null, 2)};`,
    '',
    `export const CATEGORIES = ${JSON.stringify(catalog.categories, null, 2)};`,
    '',
    `export const SCOPE_INFO = ${JSON.stringify(catalog.scopes, null, 2)};`,
    '',
    `export const ROLE_TEMPLATES = ${JSON.stringify(catalog.templates, null, 2)};`,
    '',
  ].join('\n');
  emit('../sanctum-frontend/lib/authz/catalog.generated.ts', ts);
}

// ---------------------------------------------------------------- flutter client
{
  const camel = (key: string) =>
    key.replace(/[._]([a-z])/g, (_m, c: string) => c.toUpperCase());
  const dart = [
    `// ${HEADER}`,
    '// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars',
    '',
    `const String kCatalogVersion = ${JSON.stringify(catalog.version)};`,
    '',
    '/// Every permission key. Use these constants — never string literals.',
    'abstract final class P {',
    ...PERMISSIONS.map((p) => `  static const String ${camel(p.key)} = ${JSON.stringify(p.key)};`),
    '}',
    '',
    `const List<String> kScopes = <String>[${SCOPES.map((s) => JSON.stringify(s)).join(', ')}];`,
    '',
    'class PermissionMeta {',
    '  const PermissionMeta(this.key, this.category, this.label, this.scopes, this.sensitive);',
    '  final String key;',
    '  final String category;',
    '  final String label;',
    '  final List<String> scopes;',
    '  final bool sensitive;',
    '}',
    '',
    'const List<PermissionMeta> kPermissions = <PermissionMeta>[',
    ...PERMISSIONS.map(
      (p) =>
        `  PermissionMeta(${JSON.stringify(p.key)}, ${JSON.stringify(p.category)}, ${JSON.stringify(p.label)}, <String>[${p.scopes.map((s) => JSON.stringify(s)).join(', ')}], ${p.sensitive}),`,
    ),
    '];',
    '',
  ].join('\n');
  emit('../sanctum-flutter/lib/authz/catalog.g.dart', dart);
}

if (check && drift) {
  console.error('Authorization artifacts are out of date. Run: pnpm authz:generate');
  process.exit(1);
}
